---

- name: System is un-registered and un-subscribed but does not ignores errors
  redhat_subscription:
  args:
    state: absent
  register: result
  until: result | success
  retries: "{{ rhsm_retries }}"
  delay: "{{ rhsm_delay }}"
  when: (is_rhel or is_rhelah) and rhsm.unsubscribe
