---

docker_autotest:
    test_image:
        host: "docker.io"
        user:
        name: "fedora"
        tag: "latest"
        build_url:
    templates:
        - src: "{{ custom_subtests_ini_j2 | default('subtests.ini.j2') }}"
          dest: "{{ autotest_docker_path }}/config_custom/subtests.ini"
        - src: "{{ custom_control_ini_j2 | default('control.ini.j2') }}"
          dest: "{{ autotest_docker_path }}/config_custom/control.ini"
    preserve_fqins:
        - "docer.io/fedora:latest"
    preserve_cnames: []
    execute: true
    enable_bugzilla: true
