---
- name: Docker Autotest is installed
  command: /usr/bin/docker run
           {{ docker.build_args | join(' ')  }}
           {{ docker.build_fqin }}
           git clone {{ autotest_docker.repo }} /host/{{ autotest_docker_path }}
  args:
    creates: "{{ autotest_docker_path }}/control"

# Fix vim syntax highlight bug
# '

- name: Specific Docker autotest version is checked out
  command: /usr/bin/docker run
           {{ docker.build_args | join(' ') }}
           --workdir /host/{{ autotest_docker_path }}
           {{ docker.build_fqin }}
           git reset --hard {{ autotest_docker.version }}
  when: autotest_docker_is_versioned

# Fix vim syntax highlight bug
# '

- name: Latest Docker autotest version is checked out
  command: /usr/bin/docker run
           {{ docker.build_args | join(' ') }}
           --workdir /host/{{ autotest_docker_path }}
           {{ docker.build_fqin }}
           git reset --hard origin/HEAD
  when: not autotest_docker_is_versioned
