---
- name: Docker Autotest image was built
  command: /usr/bin/docker inspect --format \{\{.Created\}\}
           autotest_docker:{{ autotest_docker.version }}
  register: autotest_docker_is_built
  ignore_errors: True
  args:
    warn: no

- name: Docker Autotest image is build
  command: /usr/bin/docker run {{ autotest_docker_build.spc_args }}
           {{ autotest_docker_build.spc_fqin }}
           /usr/bin/docker build
           --quiet
           --tag autotest_docker:{{ autotest_docker.version }}
           {{ autotest_docker.repo }}
  when: autotest_docker_is_built|failed

- name: Docker Autotest is installed
  command: /usr/bin/atomic install
           autotest_docker:{{ autotest_docker.version }}
  args:
    creates: "{{ autotest.path }}/client/tests/docker/control"
