---
- name: Docker Autotest {{ autotest_docker.version }} control timeout set
  lineinfile:
  args:
    - backrefs: True
    - dest: "{{ autotest.path }}/client/tests/docker/control"
    - follow: True
    - line: "\\1 {{ autotest_docker.timeout }}"
    - regexp: "^(TIMEOUT\\s*=\\s*).*$"
    - backup: True

- name: Docker Autotest {{ autotest_docker.version }} control is configured
  ini_file:
  args:
    dest: "{{ autotest.path }}/client/tests/docker/config_custom/control.ini"
    option: include
    section: Control
    value: '{{ autotest_docker.subtests | join(",") }}'

- name: Default Test image name is configured
  ini_file:
  args:
    dest: "{{ autotest.path }}/client/tests/docker/config_custom/defaults.ini"
    option: docker_repo_name
    section: DEFAULTS
    value: "{{ autotest_docker.test_image.name }}"

- name: Default Test image tag is configured
  ini_file:
  args:
    dest: "{{ autotest.path }}/client/tests/docker/config_custom/defaults.ini"
    option: docker_repo_tag
    section: DEFAULTS
    value: "{{ autotest_docker.test_image.tag }}"

- name: Default Test registry host is configured
  ini_file:
  args:
    dest: "{{ autotest.path }}/client/tests/docker/config_custom/defaults.ini"
    option: docker_registry_host
    section: DEFAULTS
    value: "{{ autotest_docker.test_image.host }}"

- name: Default Test registry user is configured
  ini_file:
  args:
    dest: "{{ autotest.path }}/client/tests/docker/config_custom/defaults.ini"
    option: docker_registry_user
    section: DEFAULTS
    value: "{{ autotest_docker.test_image.user }}"
