---
- name: EPEL Release 7 is installed
  yum:
  args:
    name: http://dl.fedoraproject.org/pub/epel/7/{{ ansible_machine }}/e/epel-release-7-5.noarch.rpm
    state: present
  when: ansible_distribution_major_version == 7

- name: EPEL Release 6 is installed
  yum:
  args:
    name: http://dl.fedoraproject.org/pub/epel/6/{{ ansible_machine }}/epel-release-6-8.noarch.rpm
    state: present
  when: ansible_distribution_major_version == 6
