---

# Depends:
#   - kommandir_workspace
#   - kommandir_sync_excludes
#   - adept_path

- name: kommandir workspace adept path excluded temporarily
  set_fact:
    _kwape:
        - "--exclude=adept/***"

- name: kommandir workspace transfered to controller host
  synchronize:
    mode: pull
    compress: True
    dest: '{{ workspace }}/'
    links: True
    perms: True
    recursive: True
    # Don't trust clocks or mod-times
    checksum: True
    # Copy contents to dest, not src directory itself
    src: '{{ kommandir_workspace }}/'
    rsync_opts: '{{ kommandir_sync_excludes |
                    union(_kwape) }}'
  # Rarely should need to debug the massive list of files
  no_log: true

- name: kommandir adept transfered to controller host
  synchronize:
    mode: pull
    compress: True
    dest: '{{ adept_path }}/'
    links: True
    perms: True
    recursive: True
    # Don't trust clocks or mod-times
    checksum: True
    # Copy contents to dest, not src directory itself
    src: '{{ kommandir_workspace }}/adept/'
    rsync_opts: '{{ kommandir_sync_excludes }}'
  # Rarely should need to debug the massive list of files
  no_log: true
