---
- include: ../../common/site_scripts.yml.inc

- name: Support packages are installed
  yum:
  args:
    name: "{{ install_rpms }}"
    state: present
  register: support_installed
  notify:
    - The needs_reboot flag is set because of install or package update

- name: System is fully updated
  yum:
  args:
    name: "*"
    state: latest
  register:
    system_updated
  notify:
    - The needs_reboot flag is set because of install or package update
  when: update_system
