---
# vim-syntax: yaml

disk_device: "/dev/vdb"
parted_cmds: "unit % mklabel msdos mkpart primary 0 100 set 1 LVM on"

lvg_ops:
    - vg: docker_vg
      force: yes
      pvs: '{{ disk_device }}1'
      state: present
lvol_ops:
    - lv: swap
      size: 512
      state: present
      vg: docker_vg

swap_device: /dev/docker_vg/swap
