---

# Bootstraps an Atomic Host with ability to run Adept slave container
# under a controlled environment.  Only openstack is supported at the moment.

# N/B: Don't assume Ansible > 1.94

- hosts: localhost
  any_errors_fatal: true
  vars_files:
    - "group_vars/kommandir"
  roles:
    - common
  tasks:
    - include: roles/kommandir/tasks/openstack.yml
      when: kommandir_type == 'openstack' and
            adept_context == 'setup'

    # TODO add support for other kommandir_type's

    # Otherwise unknown outside of setup context
    - include: roles/kommandir/tasks/get_kmndrip.yml

    - include: roles/kommandir/tasks/update_inventory.yml
      when: adept_context == 'setup'

    # Depends on roles/kommandir/tasks/get_kmndrip.yml
    - name: kommandir ssh port is listening
      wait_for:
        port: "22"
        host: '{{ kmndrip }}'
        timeout: 300

- hosts: sync_out
  roles:
    - kommandir
    - sync_out

- hosts: sync_back
  roles:
    - sync_back
