---
- hosts: all
  roles:
    - redhat_release

# These groups are defined dynamicly from
# redhat_release role, based on release_name value (above)

- hosts: subscribed
  roles:
    - subscribed

- hosts: rhel:centos
  roles:
    - epel

- hosts: rhel
  roles:
    - rhel

- hosts: rhelah
  roles:
    - rhelah

- hosts: centos
  roles:
    - centos

- hosts: fedora
  roles:
    - fedora

- hosts: all
  roles:
    - { role: rebooted, when: needs_reboot }
