---

- hosts: subscribed
  roles:
    - subscribed

- hosts: rhel
  roles:
    - rhel
    - se_enabled

- hosts: rhelah
  roles:
    - rhelah

- hosts: centos
  roles:
    - centos
    - se_enabled

- hosts: fedora
  roles:
    - fedora
    - se_enabled

- hosts: fedoratomic
  roles:
    - fedoratomic

- hosts: all
  roles:
    - { role: rebooted, when: needs_reboot }
