---
- hosts: all
  roles:
    - redhat_release
    # These groups are defined dynamicly from
    # redhat_release role (above), conditionally
    # assigned here to increase parallelism and
    # and prevent unnecessary dependency following
    - { role: subscribed, when: "'subscribed' in group_names" }
    - { role: rhel, when: "'rhel' in group_names" }
    - { role: rhelah, when: "'rhelah' in group_names" }
    - { role: centos, when: "'centos' in group_names" }
    - { role: fedora, when: "'fedora' in group_names" }
    - { role: epel, when: "'epel' in group_names" }
