---

- hosts: subscribed
  roles:
    - subscribed

- hosts: rhel
  roles:
    - rhel

- hosts: rhelah
  roles:
    - rhelah

- hosts: centos
  roles:
    - centos

- hosts: fedora
  roles:
    - fedora

- hosts: fedoratomic
  roles:
    - fedoratomic

- hosts: all
  roles:
    - { role: rebooted, when: needs_reboot }
