---

# Ensure slave is in the right groups
- include: localhost.yml

# Necessary for dynamic inventory
- hosts: openstack
  any_errors_fatal: true
  roles:
    - role: openstack

- hosts: autotested:&{{ adept_job }}
  roles:
    - role: autotested
      # Last task of peon setup sets this in host_vars
      when: touchstone_touched | default(False)
  post_tasks:
    - debug:
        msg: "Host did not successfully complete setup"
      when: not (touchstone_touched | default(False))
