---

# Ensure slave is in the right groups
- include: localhost.yml

# Necessary for dynamic inventory
- hosts: openstack
  roles:
    - role: openstack

- hosts: autotested:&{{ adept_job }}
  roles:
    - role: autotested
