---

- name: Support packages are installed
  yum:
  args:
    name: docker-io,atomic,procps,tar,findutils,bzip2,gdb,bridge-utils,nfs-utils,git,glibc-devel,python-sphinx,python-bugzilla,which,pylint,make,python-pep8,python-sphinxcontrib-httpdomain
    state: present
  register: support_installed
  notify:
    - The needs_reboot flag is set because of install or package update

- name: System is fully updated
  yum:
  args:
     name: "*"
     state: latest
  register:
    system_updated
  notify:
    - The needs_reboot flag is set because of install or package update
  when: update_system
