---

- include: ../../../roles/common/tasks/workspace_file.yml
  vars:
    workspace_file: ssh_private_key
    workspace: "{{ kommandir_workspaces }}/{{ adept_job }}"

- name: runtime ssh-key is generated
  shell: >
    [ -r "{{ kommandir_workspaces }}/{{ adept_job }}/ssh_private_key" ] || \
        ssh-keygen -f "{{ filepath }}" \
                   -q \
                   -N ""
  when: not exists

- name: workaround bugzilla 1357116
  lineinfile:
    dest: /etc/sysconfig/docker-network
    regexp: DOCKER_NETWORK_OPTIONS.*
    line: DOCKER_NETWORK_OPTIONS=--mtu=1400
    state: present
  notify: restart docker service
