---

- name: runtime ssh-key is generated
  shell: >
    [ -r "{{ kommandir_workspaces }}/{{ adept_job }}/ssh_private_key" ] || \
        ssh-keygen -f "{{ kommandir_workspaces }}/{{ adept_job }}/ssh_private_key" \
                   -q \
                   -N ""
