---

# Depends:
#   - kommandir_workspaces
#   - kommandir_sync_excludes
#   - adept_job

- name: status of kommandir workspace directory is known
  stat:
    path: '{{ kommandir_workspaces }}/{{ adept_job }}'
  register: _exists

- name: kommandir workspace does exist
  set_fact:
    _exists: True
  when: _exists.stat is defined and
        _exists.stat.exists and
        _exists.stat.isdir

- name: kommandir workspace does not exist
  set_fact:
    _exists: False
  when: _exists.stat is defined

- name: kommandir workspace adept path excluded temporarily
  set_fact:
    _kwape:
        - "--exclude={{ kommandir_workspaces }}/{{ adept_job }}/adept"

- name: kommandir workspace transfered to controller host
  synchronize:
    mode: pull
    compress: True
    dest: '{{ workspace }}'
    links: True
    perms: True
    recursive: False
    # Copy contents to dest, not src directory itself
    src: '{{ kommandir_workspaces }}/{{ adept_job }}/*'
    rsync_opts: '{{ kommandir_sync_excludes |
                    union(_kwape) }}'
  when: _exists

- name: kommandir adept group_vars transfered to controller host
  synchronize:
    mode: pull
    compress: True
    dest: '{{ adept_path }}'
    links: True
    perms: True
    recursive: True
    # Copy contents to dest, not src directory itself
    src: '{{ kommandir_workspaces }}/{{ adept_job }}/adept/*'
    rsync_opts: '{{ kommandir_sync_excludes }}'
  when: _exists
