---

# These variables apply to all hosts in the autotest_docker group
# as defaults.  To modify variables for a specific host, copy this
# file into the host_vars directory, named as the dns name
# of the host.

autotest:
    # Git repository where autotest should be cloned
    # from.  This can point upstream, to a fork or
    # custom repo.  However, it must provide the version
    # specified by autotest_docker.version shown by
    # running client/shared/version.py
    repo: https://github.com/autotest/autotest.git

    # Path where autotest will be installed.
    path: /usr/local/autotest

docker:
    # Fully-qualified image name of build container to use
    # for building/installing autotest and autotest_docker.
    # This prevents needing additional packages/software on
    # the test host which could affect testing.
    build_fqin: registry.access.redhat.com/rhel7/rhel-tools:latest

    # List of additional arguments to pass when running
    # build/installation steps.  Install destination root
    # is assumed to be /host
    build_args:
        - --interactive
        - --rm
        - --privileged
        - --net=host
        - --ipc=host
        - --pid=host
        - --env DESTROOT=/host
        - --volume /run:/run
        - --volume /var/log:/var/log
        - --volume /:/host
