---

- name: System is registered and subscribed
  redhat_subscription:
  args:
    autosubscribe: yes
    username: "{{ rhsm.username }}"
    password: "{{ rhsm.password }}"
    state: present
  register: result
  until: result | success
  retries: rhsm_retries
  delay: rhsm_delay
  when: is_rhel or is_rhelah
