---

- name: System is registered and subscribed
  redhat_subscription:
  args:
    autosubscribe: yes
    username: "{{ rhsm.username }}"
    password: "{{ rhsm.password }}"
    state: present
  register: result
  until: result | success
  retries: "{{ rhsm_retries }}"
  delay: "{{ rhsm_delay }}"
  when: rhsm.username is defined and
        rhsm.username != [] and
        rhsm.password is defined and
        rhsm.password != []
