---
- name: System is registered and subscribed
  redhat_subscription:
  args:
    autosubscribe: yes
    username: "{{ rhsm.username }}"
    password: "{{ rhsm.password }}"
    state: present
  when: is_rhel or is_rhelah
