---

# older ansible needs the path this way
- include: ../../../roles/common/tasks/workspace_file.yml
  vars:
    workspace_file: "KOMMANDIR_NAME"

- name: Kommandir name is defined from KOMMANDIR_NAME file
  set_fact:
    kmndrname: '{{ lookup("file",filepath) | lower }}'
  when: exists
  delegate_to: localhost

- fail:
    msg: "KOMMANDIR_NAME file does not exist in worksapce"
  when: not exists
