---

# There are situations where default repositories are broken
# - name: All repositories are disabled
#   command: /usr/sbin/subscription-manager repos --disable=*

- name: epel-release RPM copied to host
  copy:
    src: epel-release-latest-7.noarch.rpm
    dest: /root/
  register: copied

- name: epel repository is installed
  include: roles/installed/tasks/main.yml
  vars:
    installed_rpms:
        - /root/epel-release-latest-7.noarch.rpm
    installed_enablerepo: []
    installed_disablerepo: []
  when: copied | changed
