---
- name: Repo. disable list is defined
  set_fact:
    yum_disable_repos: "*-eus-*,*-htb-*,*-ha-*,*-rt-*,*-lb-*,*-rs-*,*-sap-*,*beta*"

- name: Repo. enable list is defined
  set_fact:
    yum_enable_repos: "*-optional-rpms,*-extras-rpms,*7-server-rpms,*7-server-eus-rpms,*epel*,base,extras,updates"

- name: Support packages are installed
  yum:
  args:
    name: docker,atomic,procps,tar,findutils,bzip2,gdb,bridge-utils,nfs-utils,git,glibc-devel,python-sphinx,python-bugzilla,which,pylint,make,python-pep8,python-sphinxcontrib-httpdomain
    state: present
    disablerepo: "{{ yum_disable_repos }}"
    enablerepo: "{{ yum_enable_repos }}"
  register: support_installed
  notify:
    - The needs_reboot flag is set because of install

- name: System is fully updated
  yum:
  args:
    name: "*"
    state: latest
    disablerepo: "{{ yum_disable_repos }}"
    enablerepo: "{{ yum_enable_repos }}"
  register:
    system_updated
  notify:
    - The needs_reboot flag is set because of update
  when: update_system
