---

- block:

    - name: epel-release RPM copied to host
      copy:
        src: epel-release-latest-7.noarch.rpm
        dest: /root/
      register: copied

    - name: epel repository is installed
      include: roles/installed/tasks/main.yml
      vars:
        installed_rpms:
            - /root/epel-release-latest-7.noarch.rpm
        installed_enablerepo: []
        installed_disablerepo: []
      when: copied | changed

  when: installed_enablerepo is defined and
        'epel' in installed_enablerepo

- block:

    # There are situations where default repositories are broken
    - name: All repositories are disabled in subscription manager
      command: /usr/sbin/subscription-manager repos --disable=*

    - name: Explicit list of repositories enabled in subscription manager
      command: /usr/sbin/subscription-manager repos --enable={{ item }}
      when: installed_enablerepo is defined and
            installed_enablerepo != [] and
            not item | search('epel')
      with_items: '{{ installed_enablerepo }}'

  when: disable_all_rh_repos
