---

# Depends:
#   is_atomic
# Registers:
#   rpms_updated: boolean
#   needs_reboot: boolean

- fail:
    msg: "Attempt to apply the atomic_upgrade role onto a non-Atomic host"
  when: not is_atomic

- name: Record upgrade diff check output
  command: atomic host upgrade --check-diff
  register: upgrade_check
  # BZ1313540
  ignore_errors: true

- name: Set _needs_upgrade flag False when indicated by atomic command
  set_fact:
    _needs_upgrade: False
  when: (upgrade_check.rc == 0 or atomic_host_upgrade.rc == 77) and
        upgrade_check.stdout | search('No upgrade available.')

- name: Set _needs_upgrade flag True
  set_fact:
    _needs_upgrade: True
  when: _needs_upgrade is undefined

- name: Atomic host is updated to latest tree
  command: atomic host upgrade
  register: atomic_host_upgrade
  changed_when: atomic_host_upgrade.rc == 0 or
                atomic_host_upgrade.rc == 77
  ignore_errors: true
  when: _needs_upgrade

- name: Workaround BZ1313540
  fail:
    msg: "atomic host upgrade failed with unknown error: {{ atomic_host_upgrade }}"
  when: atomic_host_upgrade.rc != 0 and atomic_host_upgrade.rc != 77

- name: rpms_updated is set on update
  set_fact:
    rpms_updated: '{{ atomic_host_upgrade | changed }}'
    needs_reboot: '{{ atomic_host_upgrade | changed }}'
