---

# Depends:
#   - peon
#   - openstack

- debug:
    msg: "Working on peon: {{ peon.uuid }}"

- name: private security group is used when sec_mode is True
  set_fact:
    _secgrps: '{{ openstack.private_sec_groups }}'
  when: peon.private

- name: public security group is used when sec_mode is False
  set_fact:
    _secgrps: '{{ openstack.public_sec_groups }}'
  when: _secgrp is undefined

- name: metadata is defined
  set_fact:
    metadata:
        hostname: '{{ peon.uuid }}'
        groups: '{{ peon.groups | join(",") }}'

- name: peon from peon_set is provisioned
  os_server:
    cloud: default
    flavor: "m1.medium"
    image: '{{ openstack.image_map[peon.name][peon.version] }}'
    name: '{{ peon.uuid }}'
    #key_name: '{{ openstack.key_name }}'
    security_groups: '{{ _secgrps }}'
    auto_ip: False
    userdata: |
        {{ "#cloud-config" }}
        {{ openstack.userdata | to_nice_yaml }}
    meta: "{{ metadata }}"
    # Returns faster with this
    # Unknown if this could race with items below
    wait: False
  register: _created

- name: peon has IP addresses
  os_floating_ip:
    network: '{{ openstack.public_network }}'
    cloud: default
    reuse: True
    server: '{{ peon.uuid }}'
    state: present
    # Returns faster with this
    # Unknown if this could race with items above
    wait: False
  when: _created.openstack is defined and
        _created.openstack.public_v4 is undefined or
        _created.openstack.public_v4|trim == ""
