---

# depends:
#   peon_set
# registers:
#   peon_facts

- include: roles/common/tasks/workspace_file.yml
  vars:
    workspace_file: "peon_facts.yml"

- name: peon_facts.yml file is loaded
  set_fact:
    peon_facts: '{{ lookup("file", filepath) | from_yaml }}'
  when: exists

- block:
    - name: peon facts buffer is initially empty
      set_fact:
        _peon_facts: {}

    - include: roles/openstack/tasks/facts_peons.yml
      with_items: "{{ peon_set }}"
      loop_control:
        loop_var: peon

    - fail:
        msg: "peon_facts buffer is empty"
      when: _peon_facts == {}

    - name: peon facts buffer is written out to disk
      copy:
        dest: "{{ filepath }}"
        content: "{{ _peon_facts | to_nice_yaml }}"

    # Exit the block
    - name: peon facts map is updated from buffer
      set_fact:
        peon_facts: '{{ _peon_facts }}'

  when: peon_facts is undefined

- name: setup runs on all newly added peons
  setup:
  delegate_facts: true
  delegate_to: '{{ item }}'
  with_inventory_hostnames: peons:&{{ adept_job }}
