---
autotest-docker:
    repo: https://github.com/autotest/autotest-docker.git
    version: latest
    test_image:
        name: rhel-tools
        tag: latest
        host: registry.access.redhat.com
        user: rhel7
    # 10-minutes at most
    timeout: 600
    subtests:
        - docker_cli/dockerhelp
        - docker_cli/version
        - docker_cli/run_cgroups
        - docker_cli/build/https_file
