---

use_dnf: False
installed_enablerepo:
    - epel
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-optional-rpms
    - rhel-7-server-supplementary-rpms
installed_rpms:
    - docker
    - atomic
    - docker-selinux
    - procps
    - tar
    - lvm2
    - findutils
    - bzip2
    - gdb
    - bridge-utils
    - nfs-utils
    - git
    - glibc-devel
    - python-bugzilla
    - which
    - cloud-utils-growpart
    - python-nose
    - python-unittest2
    - python2-mock
    - python-docutils
    - python-sphinx
    - python-sphinxcontrib-httpdomain
    - python-sphinx_rtd_theme
    - selinux-policy-targeted
    - libselinux-python
    - iputils
