---
- name: Red Hat Release is known
  command: cat /etc/redhat-release
  register: cat_redhat_release
  changed_when: False

- name: Red Hat Release has no codename
  set_fact:
    redhat_release: "{{ cat_redhat_release.stdout
                        | regex_replace('\\s+\\(.+\\)', '') }}"

- name: Red Hat Release has only name
  set_fact:
    redhat_release: "{{ redhat_release
                        | regex_replace('\\s+release\\s+.+$', '') }}"

- name: Red Hat Release booleans default to False
  set_fact:
    is_atomic: false
    is_rhel: false
    is_centos: false
    is_fedora: false

- name: Red Hat Release is RHEL Atomic
  set_fact:
    is_atomic: true
    release_name: rhelah
  when: redhat_release | match('.*Atomic Host.*')

- name: Red Hat Release is RHEL Server
  set_fact:
    is_rhel: true
    release_name: rhel
  when: not is_atomic and
        redhat_release | match('.*Red Hat Enterprise Linux.*')

- name: Red Hat Release is CentOS
  set_fact:
    is_centos: true
    release_name: centos
  when: not is_rhel and
        redhat_release | match('.*CentOS.*')

- name: Red Hat Release is Fedora
  set_fact:
    is_fedora: true
    release_name: fedora
  when: not is_centos and
        redhat_release | match('.*Fedora.*')

- name: Red Hat Release boolean set
  assert:
    that: is_atomic or is_rhel or is_centos or is_fedora
