---
- name: RHSM Details include file-list is defined
  set_fact:
    rhsm_detail_files:
        - "{{ release_name }}_{{ ansible_distribution_version }}.yml"
        - "{{ release_name }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ release_name }}.yml"
        - "rhsm_defaults.yml"

- name: RHSM Details vars are included
  include_vars: "{{ item }}"
  with_first_found: rhsm_detail_files
