---

# depends:
#   - workspace_file: relative path
# registers:
#   - filepath
#   - exists

- include: roles/common/tasks/workspace.yml

- name: full path to file is formed
  set_fact:
    filepath: "{{ workspace }}/{{ workspace_file }}"

- debug:
    msg: "Checking for existance of {{ filepath }}"

- name: status of file is retrieved
  stat:
    path: '{{ filepath }}'
  register: exists

- name: file exists
  set_fact:
    exists: True
  when: exists.stat.exists and exists.stat.isreg

- name: file does not exist
  set_fact:
    exists: False
  when: exists.stat is defined
