---
# Red Hat Subscription Manager activation credentials for test resources.
# Pull from file-contents by default, omit to bypass activation.
rhsm:
    username: "{{ lookup('file', '~/rhn_username') | default(omit) }}"
    password: "{{ lookup('file', '~/rhn_password') | default(omit) }}"
    # Set true to unsubscribe system at end of testing
    unsubscribe: false

# Set the number of acceptable subscription failures
rhsm_retries: '5'
rhsm_delay: '30'
