---

- block:

    - name: docker service is stopped
      service:
        name: docker
        state: stopped

    - debug:
        var: "sysconfig_dss_dest"

    - name: render sysconfig_dss_dest from template
      template:
        backup: True
        dest: "{{ sysconfig_dss_dest }}"
        src: "{{ sysconfig_dss_template }}"
      when: sysconfig_dss_template != ""

    - block:

        - name: Comment out all sysconfig_dss_dest lines
          replace:
            backup: True
            dest: "{{ sysconfig_dss_dest }}"
            regexp: "^(.*)"
            replace: "# \\1"

        - name: Add lines to sysconfig_dss_dest
          lineinfile:
            backup: False
            dest: "{{ sysconfig_dss_dest }}"
            line: "{{ item }}"
          with_items: '{{ sysconfig_dss_lines }}'

      when: sysconfig_dss_lines != []

    - name: docker storage is (re)configured
      command: docker-storage-setup
      register: result

  when: sysconfig_dss_template != "" or
        sysconfig_dss_lines != []
