---

- block:

    - name: docker service is stopped
      service:
        name: docker
        state: stopped

    - name: render sysconfig/d-s-s & latest, from template
      template:
        backup: True
        dest: "{{ item }}"
        src: "{{ sysconfig_dss_template }}"
      when: sysconfig_dss_template != ""
      with_items:
        - "/etc/sysconfig/docker-storage-setup"
        - "/etc/sysconfig/docker-latest-storage-setup"

    - block:

        - name: Comment out all sysconfig/d-s-s & latest, lines
          replace:
            backup: True
            dest: "{{ item }}"
            regexp: "^(.*)"
            replace: "# \\1"
          with_items:
            - "/etc/sysconfig/docker-storage-setup"
            - "/etc/sysconfig/docker-latest-storage-setup"

        - name: Add lines to sysconfig/d-s-s
          lineinfile:
            backup: False
            dest: "/etc/sysconfig/docker-storage-setup"
            line: "{{ item }}"
          with_items: '{{ sysconfig_dss_lines }}'

        - name: Add lines to sysconfig/d-s-s latest
          lineinfile:
            backup: False
            dest: "/etc/sysconfig/docker-latest-storage-setup"
            line: "{{ item }}"
          with_items: '{{ sysconfig_dss_lines }}'

      when: sysconfig_dss_lines != []

    - name: docker storage is (re)configured
      command: docker-storage-setup
      register: result

  when: sysconfig_dss_template != "" or
        sysconfig_dss_lines != []
