---
- name: Docker Autotest {{ autotest-docker.version }} results do not exist
  command: rm -rf {{ autotest.path }}/client/results/default
  args:
    removes: "{{ autotest.path }}/client/results/default"

- name: Autotest is executed
  shell: "AUTOTEST_PATH={{ autotest.path }}
          {{ autotest.path }}/client/autotest-local run docker &> /dev/null"
  args:
    creates: "{{ autotest.path }}/client/results/default/status"
  async: 14401
  poll: 30

- name: Autotest verbose results exist
  shell: tar -cjf /tmp/results.tbz results
  args:
    chdir: "{{ autotest.path }}/client"

- name: Autotest JUnit results exist
  shell: tools/results2junit.py
         results/default
         | tee /tmp/results.junit
  args:
    chdir: "{{ autotest.path }}/client"
