---
# vim-syntax: yaml

disk_device: "/dev/vdb"
parted_cmds: "unit % mklabel msdos mkpart primary 0 100 set 1 LVM on"

lvg_ops:
    - vg: docker_vg
      force: yes
      pvs: '{{ disk_device }}1'
      state: present

use_dnf: False
installed_enablerepo:
    - base
    - extras
    - epel
    - updates
installed_rpms:
    - docker
    - atomic
    - docker-selinux
    - procps
    - tar
    - findutils
    - bzip2
    - gdb
    - lvm2
    - bridge-utils
    - nfs-utils
    - git
    - glibc-devel
    - python-bugzilla
    - which
    - cloud-utils-growpart
    - python-nose
    - python-unittest2
    - python2-mock
    - python-docutils
    - python-sphinx
    - python-sphinxcontrib-httpdomain
    - python-sphinx_rtd_theme
    - selinux-policy-targeted
    - libselinux-python
