---

# Depends:
#   - lvg_ops: list of parameter dictionaries for lvg module
#   - lvol_ops: list of parameter dictionaries for lvol module
# Registers:

# Condition should apply to task, not each iteration
- block:

    # All atomic hosts are setup w/ LVM by default
    - include: roles/common/tasks/is_atomic.yml

    - include: roles/installed/tasks/main.yml
      vars:
        installed_rpms:
            - lvm2
            - lvm2-libs
        installed_enablerepo:
        installed_disablerepo:
      when: not is_atomic

    - name: lvg module commands are executed
      lvg:
        force: '{{ item.force | default(omit) }}'
        pesize: '{{ item.pesize | default(omit) }}'
        pvs: '{{ item.pvs | default(omit) }}'
        state: '{{ item.state | default(omit) }}'
        vg: '{{ item.vg | default(omit) }}'
        vg_options: '{{ item.vg_options | default(omit) }}'
      with_items: '{{ lvg_ops }}'

  when: lvg_ops != []

# Condition should apply to task, not each iteration
- block:

    - name: lvol module commands are executed
      lvol:
        force: '{{ item.force | default(omit) }}'
        lv: '{{ item.lv | default(omit) }}'
        opts: '{{ item.opts | default(omit) }}'
        size: '{{ item.size | default(omit) }}'
        snapshot: '{{ item.snapshot | default(omit) }}'
        state: '{{ item.state | default(omit) }}'
        vg: '{{ item.vg | default(omit) }}'
      with_items: '{{ lvg_ops }}'

  when: lvol_ops != []
