---

- name: Reboot System
  shell: "sleep 3 && shutdown -r 1"
  async: 1
  poll: 0
  changed_when: true
  ignore_errors: true

- name: Pre-reboot uptime in seconds is known just before reboot
  shell: sleep 48s && cat /proc/uptime | cut -d " " -f 1 | cut -d "." -f 1
  register: pre_result

- debug: msg="Pre-reboot uptime is {{ pre_result.stdout }}s"

- name: Pause for remainder of Shutdown/Reboot for port 22 to close
  pause:
    seconds: "{{ shutdown_timeout }}"
  delegate_to: 127.0.0.1

- name: System has booted back up
  local_action: wait_for host={{ inventory_hostname }}
                port=22
                timeout={{ bootup_timeout }}

# Because 'shutdown -r' (above) has ignore_errors: true, system may not
# have actually rebooted.  Verify it has by examining uptime duration
# and comparing to minimum shutdown_timeout delay.
- name: Post-reboot uptime in seconds is known
  shell: cat /proc/uptime | cut -d " " -f 1 | cut -d "." -f 1
  register: post_result

- debug: msg="Post-reboot uptime is {{ post_result.stdout }}s"

- fail:
  args:
    msg: "Post-reboot uptime {{ post_result.stdout }}s longer than pre-reboot uptime {{ pre_result.stdout }}s"
  when: "{{ post_result.stdout | int }} >= {{ pre_result.stdout | int }}"
