---
# Fire-and-forget mode, independent of command exit-status
- name: Reboot System
  shell: '( /usr/bin/sleep 1s && /usr/sbin/reboot ) &'
  ignore_errors: true
  async: 0
  poll: 0
  changed_when: true

# Locally, check port every 13 seconds (DNS timeout x2)
- name: Server's ssh port is unavailable
  local_action: wait_for
                host={{ ansible_nodename | default(ansible_fqdn) }}
                port=22
                state=stopped
                connect_timeout=13
                timeout={{ shutdown_timeout }}
  # Don't use sudo on local_action
  sudo: false

- name: Server's ssh port is available
  local_action: wait_for
                host={{ ansible_nodename | default(ansible_fqdn) }}
                port=22
                state=started
                connect_timeout=13
                timeout={{ bootup_timeout }}
  notify: Remote commands can execute
  sudo: false
